config/routes.rb
Rails.application.routes.draw do

  resources :souveniors
  root :to => 'souveniors#index'

end

app/models/souvenior.rb
class Souvenior < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/souveniors_controller.rb
class SouveniorsController < ApplicationController
  before_action :set_souvenior, only: [:show, :edit, :update, :destroy]

  # GET /souveniors
  # GET /souveniors.json
  def index
    @souveniors = Souvenior.all
  end

  # GET /souveniors/1
  # GET /souveniors/1.json
  def show
  end

  # GET /souveniors/new
  def new
    @souvenior = Souvenior.new
  end

  # GET /souveniors/1/edit
  def edit
  end

  # POST /souveniors
  # POST /souveniors.json
  def create
    @souvenior = Souvenior.new(souvenior_params)

    respond_to do |format|
      if @souvenior.save
        format.html { redirect_to root_path, notice: 'Souvenior was successfully created.' }
        format.json { render :show, status: :created, location: @souvenior }
      else
        format.html { render :new }
        format.json { render json: @souvenior.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /souveniors/1
  # PATCH/PUT /souveniors/1.json
  def update
    respond_to do |format|
      if @souvenior.update(souvenior_params)
        format.html { redirect_to @souvenior, notice: 'Souvenior was successfully updated.' }
        format.json { render :show, status: :ok, location: @souvenior }
      else
        format.html { render :edit }
        format.json { render json: @souvenior.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_souvenior
      @souvenior = Souvenior.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def souvenior_params
      params.require(:souvenior).permit(:score, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SouvCheck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/souveniors/_form.html.erb
<%= form_for(@souvenior) do |f| %>
  <% if @souvenior.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@souvenior.errors.count, "error") %> prohibited this souvenior from being saved:</h2>

      <ul>
      <% @souvenior.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.radio_button :score, 0, :checked => true %>
    <%= f.label :score, 'green tea kitkat' %>

    <%= image_tag "kitkat.jpg", :size => "256x256" %>
    <br>    <br>    <br>

    <%= f.radio_button :score, 1, :checked => false %>
    <%= f.label :score, 'black thunder' %>

    <%= image_tag "blackthunder.jpeg", :size => "256x256" %>
    <br>    <br>    <br>

    <%= f.radio_button :score, 2, :checked => false %>
    <%= f.label :score, 'caramel corn' %>

    <%= image_tag "caramelcorn.jpg", :size => "256x256" %>
    <br>    <br>    <br>

    <%= f.radio_button :score, 3, :checked => false %>
    <%= f.label :score, 'habanero' %>

    <%= image_tag "habanero.jpg", :size => "256x256" %>
    <br>    <br>    <br>

    <%= f.radio_button :score, 4, :checked => false %>
    <%= f.label :score, 'happy turn' %>

    <%= image_tag "happyturn.jpg", :size => "256x256" %>
    <br>    <br>    <br>

    <%= f.radio_button :score, 5, :checked => false %>
    <%= f.label :score, 'karamu-cho' %>

    <%= image_tag "karamucho.jpg", :size => "256x256" %>
    <br>    <br>    <br>

    <%= f.radio_button :score, 6, :checked => false %>
    <%= f.label :score, 'pocky' %>

    <%= image_tag "pocky.jpeg", :size => "256x256" %>
    <br>    <br>    <br>

    <%= f.radio_button :score, 7, :checked => false %>
    <%= f.label :score, 'to-ri mon' %>

    <%= image_tag "torimon.jpg", :size => "256x256" %>
    <br>    <br>    <br>

  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/souveniors/index.html.erb
<h1>Listing souveniors</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @souveniors.each do |souvenior| %>
      <tr>
        <td><%= souvenior.score %></td>
        <td><%= souvenior.comment %></td>
        <td><%= link_to 'Show', souvenior %></td>
        <td><%= link_to 'Edit', edit_souvenior_path(souvenior) %></td>
        <td><%= link_to 'Destroy', souvenior, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Souvenior', new_souvenior_path %>

app/views/souveniors/new.html.erb
<h1>What did you like most?</h1>

<%= render 'form' %>

<%= link_to 'Back', souveniors_path %>

app/views/souveniors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @souvenior.score %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @souvenior.comment %>
</p>

<%= link_to 'Edit', edit_souvenior_path(@souvenior) %> |
<%= link_to 'Back', souveniors_path %>